=== jebbard/jMeta/EasyTagCore/src/main/resources/de/je/jmeta/extmanager/impl/schema/ExtensionBundleConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsi:schema xmlns="www.easytag.de/XMLSchema_v1_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema" targetNamespace="www.easytag.de/XMLSchema_v1_0">

	<!-- Root element -->
	<xsi:element name="ExtensionBundle" type="ExtensionBundleType"/>

	<!-- Root element type -->
	<xsi:complexType name="ExtensionBundleType">
		<xsi:all>
			<xsi:element name="BundleProperties" type="BundlePropertiesType" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="BundleJar" type="BundleJarType" minOccurs="0" maxOccurs="1"/>
			<xsi:element name="BundledExtensions" type="BundledExtensionsType" minOccurs="1" maxOccurs="1"/>
		</xsi:all>
		<!-- Should be chosen to be able to identify the bundle -->
		<xsi:attribute name="name" type="xsi:string" use="required"/>
		<!-- For detecting version compliance problems -->
		<xsi:attribute name="version" type="xsi:string" use="required"/>
	</xsi:complexType>

	<!-- Bundle type enumeration -->
	<xsi:simpleType name="BundleType">
		<xsi:restriction base="xsi:string">
			<xsi:enumeration value="DEFAULT"/>
			<xsi:enumeration value="CUSTOM"/>
		</xsi:restriction>
	</xsi:simpleType>

	<!-- Description of the properties of the bundle -->
	<xsi:complexType name="BundlePropertiesType">
		<xsi:all>
			<xsi:element name="Name" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Description" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Author" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Date" type="xsi:date" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Version" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Type" type="BundleType" minOccurs="1" maxOccurs="1"/>
		</xsi:all>
	</xsi:complexType>

	<!-- Optional bundle JAR file -->
	<xsi:complexType name="BundleJarType">
		<xsi:all>
			<xsi:element name="JarRelPath" type="xsi:string" minOccurs="1" maxOccurs="1"/>
		</xsi:all>
	</xsi:complexType>

	<!-- List of extensions -->
	<xsi:complexType name="BundledExtensionsType">
		<xsi:sequence>
			<xsi:element name="Extension" type="ExtensionType" minOccurs="1" maxOccurs="unbounded"/>
		</xsi:sequence>
	</xsi:complexType>

	<!-- Description of a single extension -->
	<xsi:complexType name="ExtensionType">
		<xsi:all>
			<xsi:element name="ExtensionPointId" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="Provider" type="xsi:string" minOccurs="1" maxOccurs="1"/>
			<xsi:element name="RelativePath" type="xsi:string" minOccurs="0" maxOccurs="1"/>
		</xsi:all>
		<xsi:attribute name="id" type="xsi:ID" use="required"/>
	</xsi:complexType>

</xsi:schema>

=== jebbard/jMeta/ExtManager_Test_Impl/testBundles/valid/01_fileNoBasePath/bundle04/ExtensionBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<extb:ExtensionBundle
	name="bundle04"
	version="1.0"
	xmlns:extb="www.easytag.de/XMLSchema_v1_0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="www.easytag.de/XMLSchema_v1_0 ExtensionBundleConfiguration.xsd">

   <!-- The basic properties of the bundle -->
	<BundleProperties>
		<Name>My FOURTH bundle</Name>
		<Description>My fourth description</Description>
		<Author>J. E.</Author>
		<Date>2011-01-05</Date>
		<Version>12er124efqwe</Version>
		<Type>CUSTOM</Type>
	</BundleProperties>

   <!-- List of all extensions in the bundle -->
	<BundledExtensions>
		<Extension id="D1">
			<ExtensionPointId>x2</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle004.a.MyOtherTestImple</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="D2">
			<ExtensionPointId>x1</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle004.a.TestImplCompA1</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="D3">
			<ExtensionPointId>x4</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle004.c.TestIMPLCompC1</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="D4">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle004.d.XYZImpl222</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
	</BundledExtensions>

</extb:ExtensionBundle>

=== jebbard/jMeta/EasyTagExt_DefaultBundle/bundle/ExtensionBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<extb:ExtensionBundle
	name="defJMeta"
	version="1.0"
	xmlns:extb="www.easytag.de/XMLSchema_v1_0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="www.easytag.de/XMLSchema_v1_0 ExtensionBundleConfiguration.xsd">

   <!-- The basic properties of the bundle -->
	<BundleProperties>
		<Name>Default jMeta extension bundle</Name>
		<Description>This bundle contains all of the default extensions for jMeta.</Description>
		<Author>Jens Ebert</Author>
		<Date>2011-05-05</Date>
		<Version>1.0</Version>
		<Type>DEFAULT</Type>
	</BundleProperties>

   <!-- List of all extensions in the bundle -->
	<BundledExtensions>
   	<!-- DataFormats extension for ID3v1 and ID3v1.1 -->
		<Extension id="DefaultjMetaID3v1FormatExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.ID3v1DummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataFormats extension for ID3v2.3 -->
		<Extension id="DefaultjMetaID3v23FormatExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.ID3v23DummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataFormats extension for MP3 -->
		<Extension id="DefaultjMetaMP3FormatsExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.MP3DummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataFormats extension for APEv2 -->
		<Extension id="DefaultjMetaAPEv2FormatsExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.APEv2DummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataFormats extension for Lyrics3v2 -->
		<Extension id="DefaultjMetaLyrics3v2FormatsExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.Lyrics3v2DummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataFormats extension for Ogg -->
		<Extension id="DefaultjMetaOggFormatsExtension">
			<ExtensionPointId>DataFormatsExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.dataformats.impl.OggDummyDataFormatExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>

   	<!-- DataBlocks extension for ID3v1 and ID3v1.1 -->
		<Extension id="DefaultjMetaID3v1BlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.ID3v1DataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataBlocks extension for ID3v2.3 -->
		<Extension id="DefaultjMetaID3v23BlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.ID3v23DataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataBlocks extension for MP3 -->
		<Extension id="DefaultjMetaMP3BlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.MP3DataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataBlocks extension for APEv2 -->
		<Extension id="DefaultjMetaAPEv2BlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.APEv2DataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataBlocks extension for Lyrics3v2 -->
		<Extension id="DefaultjMetaLyrics3v2BlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.Lyrics3v2DataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
   	<!-- DataBlocks extension for Ogg -->
		<Extension id="DefaultjMetaOggBlocksExtension">
			<ExtensionPointId>DataBlocksExtension</ExtensionPointId>
			<Provider>de.je.jmeta.defext.datablocks.impl.OggDataBlocksExtension</Provider>
			<RelativePath>../target/classes</RelativePath>
		</Extension>
	</BundledExtensions>

</extb:ExtensionBundle>

=== jebbard/jMeta/ExtManager_Test_Impl/testBundles/valid/03_jarAndFileWithBasePath/bundle09/ExtensionBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<extb:ExtensionBundle
	name="bundle09"
	version="1.0"
	xmlns:extb="www.easytag.de/XMLSchema_v1_0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="www.easytag.de/XMLSchema_v1_0 ExtensionBundleConfiguration.xsd">

   <!-- The basic properties of the bundle -->
	<BundleProperties>
		<Name>My bundle for base paths</Name>
		<Description>My fourth description</Description>
		<Author>J. E.</Author>
		<Date>2011-01-05</Date>
		<Version>12er124efqwe</Version>
		<Type>CUSTOM</Type>
	</BundleProperties>

	<BundleJar>
		<JarRelPath>../bundle09.jar</JarRelPath>
	</BundleJar>

   <!-- List of all extensions in the bundle -->
	<BundledExtensions>
		<Extension id="D1">
			<ExtensionPointId>x2</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle009.a.MyOtherTestImple</Provider>
		</Extension>
		<Extension id="D2">
			<ExtensionPointId>x1</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle009.a.TestImplCompA1</Provider>
		</Extension>
		<Extension id="D3">
			<ExtensionPointId>x4</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle009.c.TestIMPLCompC1</Provider>
		</Extension>
		<Extension id="D4">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle009.d.XYZImpl222</Provider>
		</Extension>
	</BundledExtensions>

</extb:ExtensionBundle>

=== jebbard/jMeta/ExtManager_Test_Impl/testBundles/valid/01_fileNoBasePath/bundle02/ExtensionBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<extb:ExtensionBundle
	name="bundle02"
	version="1.0"
	xmlns:extb="www.easytag.de/XMLSchema_v1_0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="www.easytag.de/XMLSchema_v1_0 ExtensionBundleConfiguration.xsd">

   <!-- The basic properties of the bundle -->
	<BundleProperties>
		<Name>My first bundle</Name>
		<Description>My description</Description>
		<Author>J. E.</Author>
		<Date>2011-01-01</Date>
		<Version>0.1</Version>
		<Type>DEFAULT</Type>
	</BundleProperties>

   <!-- List of all extensions in the bundle -->
	<BundledExtensions>
		<Extension id="B1">
			<ExtensionPointId>x1</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle002.a.TestImplCompA1</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="B2">
			<ExtensionPointId>x3</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle002.b.TestImplCompB1</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="B3">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle002.d.XYZImpl</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
	</BundledExtensions>

</extb:ExtensionBundle>

=== jebbard/jMeta/ExtManager_Test_Impl/testBundles/valid/01_fileNoBasePath/bundle03/ExtensionBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<extb:ExtensionBundle
	name="bundle03"
	version="1.0"
	xmlns:extb="www.easytag.de/XMLSchema_v1_0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="www.easytag.de/XMLSchema_v1_0 ExtensionBundleConfiguration.xsd">

   <!-- The basic properties of the bundle -->
	<BundleProperties>
		<Name>My third bundle</Name>
		<Description>My third description</Description>
		<Author>J. E.</Author>
		<Date>2011-01-04</Date>
		<Version>0.3</Version>
		<Type>DEFAULT</Type>
	</BundleProperties>

   <!-- List of all extensions in the bundle -->
	<BundledExtensions>
		<Extension id="C1">
			<ExtensionPointId>x3</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle003.b.TestIMPLEMENTOR</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="C2">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle003.d.XYZImpl1</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="C3">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle003.d.XYZImpl2</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
		<Extension id="C4">
			<ExtensionPointId>x5</ExtensionPointId>
			<Provider>de.je.jmeta.extmanager.test.bundle003.d.XYZImpl3</Provider>
			<RelativePath>../../../../target/classes</RelativePath>
		</Extension>
	</BundledExtensions>

</extb:ExtensionBundle>
